# Generated by Django 3.0.8 on 2020-07-25 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recordatorio',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('titulo', models.TextField(default='')),
                ('cuerpo', models.TextField(default='')),
                ('vencimiento', models.DateField()),
            ],
        ),
    ]
